# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('headshot', models.ImageField(upload_to='tmp')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Categories')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
