# Generated by Django 2.1.7 on 2019-02-24 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190209_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='headshot',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=True, to='posts.Categories'),
        ),
    ]
