# Generated by Django 2.1.7 on 2019-02-25 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20190224_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user_post',
            field=models.ForeignKey(default=None, on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
